name: Test

on:
  push:
    branches:
      - master

jobs:
  environment:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        env:
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
          PORT: ${{ secrets.PORT }}
          PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
          URL_DATABASE: ${{ secrets.URL_DATABASE }}

      - name: Use Node.js 18.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.4.0

      - name: Installing dependencies
        run: npm install

      - name: Run tests  
        run: npm test
